# Generated by Django 4.1.3 on 2023-01-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='title_en_us',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='article_en_us',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='article_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en_us',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
