# Generated by Django 4.1.3 on 2022-12-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contactformview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article_or_news',
            field=models.CharField(choices=[('NW', 'Новости'), ('AR', 'Статья')], default='NW', max_length=2),
        ),
        migrations.DeleteModel(
            name='ContactFormView',
        ),
    ]
